In [1]:
import numpy as np
import ara_plumes.concentric_circle as ic
from importlib import reload
reload(ic)

<module 'ara_plumes.concentric_circle' from '/home/grisal/github/ARA-Plumes/ara_plumes/concentric_circle.py'>

In [6]:
def test_find_max_on_boundary():
    axis = np.arange(5).reshape(-1, 1)
    # arr is surface u = x*y in positive quadrant
    arr = axis @ axis.T
    radii = [x_dist * np.sqrt(2) for x_dist in axis.flatten()]
    for x_dist, radius in zip(axis, radii):
        max_val, amax = ic._find_max_on_boundary(arr, (0,0), radius)
        # Max should be on the diagonal, i.e. x = y
        assert max_val == x_dist ** 2
        np.testing.assert_array_equal(amax, [x_dist, x_dist])
    
# test_find_max_on_boundary()

In [7]:
axis = np.arange(5).reshape(-1, 1)
# arr is surface u = x*y in positive quadrant
arr = axis @ axis.T
radii = [x_dist * np.sqrt(2) for x_dist in axis.flatten()]

In [18]:
for x_dist, radius in zip(axis,radii):
    print(x_dist**2,radius)

arr

[0] 0.0
[1] 1.4142135623730951
[4] 2.8284271247461903
[9] 4.242640687119286
[16] 5.656854249492381


array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

In [20]:
for x_dist, radius in zip(axis, radii):
    max_val, amax = ic._find_max_on_boundary(arr, (0,0), radius)
    print("max_val", max_val)
    print("amax", amax)
    print()
    # Max should be on the diagonal, i.e. x = y
    # assert max_val == x_dist ** 2
    # np.testing.assert_array_equal(amax, [x_dist, x_dist])

max_val 0
amax [0 0]

max_val 0
amax [1 0]

max_val 0
amax [3 0]

max_val 0
amax [4 0]



ValueError: zero-size array to reduction operation maximum which has no identity

In [22]:
d=5
def _get_x_values(col, r, n_points):
    x0 = np.max([0, col - r])
    x1 = np.min([d, col + r])
    return np.linspace(x0, x1, n_points)

In [25]:
x_vals = _get_x_values(0,np.sqrt(2),100)
x_vals

array([0.        , 0.01428499, 0.02856997, 0.04285496, 0.05713994,
       0.07142493, 0.08570991, 0.0999949 , 0.11427988, 0.12856487,
       0.14284985, 0.15713484, 0.17141983, 0.18570481, 0.1999898 ,
       0.21427478, 0.22855977, 0.24284475, 0.25712974, 0.27141472,
       0.28569971, 0.2999847 , 0.31426968, 0.32855467, 0.34283965,
       0.35712464, 0.37140962, 0.38569461, 0.39997959, 0.41426458,
       0.42854956, 0.44283455, 0.45711954, 0.47140452, 0.48568951,
       0.49997449, 0.51425948, 0.52854446, 0.54282945, 0.55711443,
       0.57139942, 0.5856844 , 0.59996939, 0.61425438, 0.62853936,
       0.64282435, 0.65710933, 0.67139432, 0.6856793 , 0.69996429,
       0.71424927, 0.72853426, 0.74281924, 0.75710423, 0.77138922,
       0.7856742 , 0.79995919, 0.81424417, 0.82852916, 0.84281414,
       0.85709913, 0.87138411, 0.8856691 , 0.89995409, 0.91423907,
       0.92852406, 0.94280904, 0.95709403, 0.97137901, 0.985664  ,
       0.99994898, 1.01423397, 1.02851895, 1.04280394, 1.05708

In [26]:
r = np.sqrt(2)
col=0
row = 0

y0 = np.sqrt(r**2 - (x_vals-col)**2)+row
y1 =-np.sqrt(r**2 - (x_vals-col)**2)+row

In [29]:
y0.round()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
y1.round()

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -0., -0., -0., -0., -0., -0.,  0.])